name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # enables npm provenance
    steps:
      - uses: actions/checkout@v4

      # Setup Node and create an .npmrc that uses the token from NODE_AUTH_TOKEN
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      # If your package is public and scoped (e.g., @scope/name), keep --access public.
      # For unscoped public packages, you can omit --access.
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}