
name: Publish Package to npmjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # enables npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Node and create an .npmrc that uses the token from NODE_AUTH_TOKEN
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      # Auto-increment patch version, commit, and push
      - name: Bump patch version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          npm version patch --no-git-tag-version
          git add package.json package-lock.json || true
          git commit -m "ci: bump patch version [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If your package is public and scoped (e.g., @scope/name), keep --access public.
      # For unscoped public packages, you can omit --access.
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}